### ISSUE TITLE
引用错误

### ISSUE THREAD

**Issue by happyhuizai** [jkchao/vue-admin#10]
![tim 20180423170618](https://user-images.githubusercontent.com/29218617/39117267-2d558b66-4719-11e8-9ca9-4bd378dfb3eb.png)
https://github.com/jkchao/vue-admin/blob/2b65f
![tim 20180423170726](https://user-images.githubusercontent.com/29218617/39117387-68222ab0-4719-11e8-8c7d-4e2c3fe93676.png)

0145301673f8db6c9ca62c073724b955c86/src/pages/comments/index.vue#L189

**Comment by Fartown** [comment]
相同的问题

**Comment by jkchao** [comment]
TypeScript 的模块解析机制让我有点蒙圈……，我找个时间改下😂

**Comment by jkchao** [comment]
@happyhuizai @Fartown 拼写错误 🌚
