### ISSUE TITLE
Npm run dev 失败

### ISSUE THREAD

**Issue by TRUEJASONFANS** [jkchao/vue-admin#12]
Hi jkchao,
 我用node stable 8.11.3 和 10.1.0 都不能成功install 成功，请问你用的哪个版本的Node

**Comment by jkchao** [comment]
@TRUEJASONFANS 报错截图看看

**Comment by TRUEJASONFANS** [comment]
奇怪 我在另一台能接外网的机器又没有问题， 设置淘宝源的就没有问题。 应该NPM的问题。 谢谢

**Comment by TRUEJASONFANS** [comment]
webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 23% building modules 116/164 modules 48 active ...bel-runtime/core-js/json/stringify.jsnode[6006]: ../src/node_file.cc:829:void node::fs::Stat(const FunctionCallbackInfo<v8::Value> &): Assertion `(argc) == (3)' failed.
 1: node::Abort() [/usr/local/opt/nvm/versions/node/v10.1.0/bin/node]
 2: node::InternalCallbackScope::~InternalCallbackScope() [/usr/local/opt/nvm/versions/node/v10.1.0/bin/node]
 3: node::fs::LStat(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/opt/nvm/versions/node/v10.1.0/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/opt/nvm/versions/node/v10.1.0/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/opt/nvm/versions/node/v10.1.0/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/opt/nvm/versions/node/v10.1.0/bin/node]
 7: 0x3a683438427d

**Comment by TRUEJASONFANS** [comment]
在Mac上用node v.10.1.0 run不起来, windows上可以

**Comment by jkchao** [comment]
@TRUEJASONFANS 不用淘宝源装包也是这样吗？

**Comment by TRUEJASONFANS** [comment]
@jkchao  不断删掉node_modules， 重新 install,  试了几次后 就work 了。 感觉应该是npm的问题。
