### ISSUE TITLE
typescript vue-router的问题

### ISSUE THREAD

**Issue by vivinbear** [jkchao/vue-admin#3]
问一下大佬,在组件中使用vue-router的'beforeRouteEnter','beforeRouteLeave','beforeRouteUpdate'钩子函数,registerHooks之后,怎么在组件内使用呢?谢谢大佬

**Comment by jkchao** [comment]
https://github.com/jkchao/vue-admin/blob/master/src/pages/article/release.vue#L234 这有个 beforeRouteUpdate 的使用例子。

**Comment by vivinbear** [comment]
一开始没找到,谢谢大佬
