### ISSUE TITLE
问个typescript类型的问题

### ISSUE THREAD

**Issue by vivinbear** [jkchao/vue-admin#4]
大佬,假如我要操作$ref.获得的是个什么类型啊.换句话说,在typescript中,有没有一些内置类型是原生的,比如我知道的有Node什么的
我的问题是:me.$refs[type].offsetTop会提示我offsetTop不属于前面那个类型,谢谢大佬了

**Comment by jkchao** [comment]
@vivinbear 
可以断言一下 (this.$refs[type] as HTMLFormElement). offsetTop

**Comment by vivinbear** [comment]
那类似于HTMLFormElement 和Node这类型的内置类型 在哪里可以查到文档呢?我翻了一下,没看到 我刚才直接 (<any>this.$refs[type]).offsetTop是可以解决,但这样很不地道.所以想知道内置类型可以在哪里查询到呢?好多有关typescript的内容都查不到呢.

**Comment by jkchao** [comment]
如果你用 vscode + vuter 开发的话，会有提示
![image](https://user-images.githubusercontent.com/22933931/34375980-558b20ba-eb24-11e7-8f34-c55f06abde92.png)

**Comment by vivinbear** [comment]
嗯嗯,好的大佬
