### ISSUE TITLE
可以给个账户密码吗？谢谢

### ISSUE THREAD

**Issue by yyccQQu** [jkchao/vue-admin#5]
可以给个账户密码吗？谢谢

**Comment by jkchao** [comment]
@yyccQQu 我只有一个自己用的账户- -，你可以把后端和这个项目一起跑起来就行了。

**Comment by wwb568109135** [comment]
@yyccQQu 我只有一个自己用的账户- -，你可以把后端和这个项目一起跑起来就行了。

－－－－－－－－－－

后端的项目，在那里？
