### ISSUE TITLE
未定义callback函数的参数类型

### ISSUE THREAD

**Issue by happyhuizai** [jkchao/vue-admin#9]
https://github.com/jkchao/vue-admin/b
![tim 20180423165807](https://user-images.githubusercontent.com/29218617/39116853-090bf07a-4718-11e8-9a47-66b59560ea21.png)
lob/2b65f0145301673f8db6c9ca62c073724b955c86/src/pages/set/index.vue#L293

**Comment by jkchao** [comment]
@happyhuizai 现在在 callback 里面加了参数，不报错了，但是总感觉怪怪的。。。

**Comment by happyhuizai** [comment]
你往里面传参数了，如果没有传就不用定义参数类型
